def stampa_piu_meno():
    print('+', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')
    print('-', end=' ')

def stampa_pipe():
    print('|', end=' ')
    print(' '*7, end=' ')


def stampa_griglia_2x2():
    stampa_piu_meno()
    stampa_piu_meno()
    print('+')
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_piu_meno()
    stampa_piu_meno()
    print('+')
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_piu_meno()
    stampa_piu_meno()
    print('+')

def stampa_riga_4():
    stampa_pipe()
    stampa_pipe()
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_pipe()
    stampa_pipe()
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_pipe()
    stampa_pipe()
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_pipe()
    stampa_pipe()
    stampa_pipe()
    stampa_pipe()
    print('|')
    stampa_piu_meno()
    stampa_piu_meno()
    stampa_piu_meno()
    stampa_piu_meno()
    print('+')

def stampa_griglia_4x4():
    stampa_piu_meno()
    stampa_piu_meno()
    stampa_piu_meno()
    stampa_piu_meno()
    print('+')
    stampa_riga_4()
    stampa_riga_4()
    stampa_riga_4()
    stampa_riga_4()

print('Griglia 2x2')
stampa_griglia_2x2()
print()
print('Griglia 4x4')
stampa_griglia_4x4()
